package flightsearch;

public class database {
	public static final String[][] aeropuertos = { //El elemento [0] de cada array es el aeropuerto de origen
			// GRANDES HUBS
		    {"madrid", "barcelona", "paris", "londres", "frankfurt", "roma", "newyork", "miami", "mexico", "buenosaires", "tokyo", "doha", "istanbul", "dubai", "singapur", "hongkong", "toronto", "saopaulo", "losangeles", "montreal", "seoul", "delhi", "johannesburgo", "lisboa", "malaga", "sevilla", "valencia", "grancanaria", "tenerife", "praga", "viena", "atenas"},
		    {"paris", "londres", "madrid", "barcelona", "frankfurt", "amsterdam", "roma", "lisboa", "dubai", "newyork", "montreal", "singapur", "hongkong", "doha", "delhi", "bangkok", "seoul", "tokyo", "losangeles", "lyon", "niza", "toulouse", "marsella", "milan", "napoles", "atenas"},
		    {"londres", "paris", "madrid", "newyork", "losangeles", "dubai", "hongkong", "tokyo", "singapur", "berlin", "barcelona", "miami", "mexico", "toronto", "johannesburgo", "saopaulo", "manchester", "edinburgo", "dublin", "birmingham", "glasgow"},
		    {"frankfurt", "madrid", "paris", "londres", "roma", "viena", "zurich", "istanbul", "dubai", "hongkong", "newyork", "singapur", "doha", "delhi", "bangkok", "tokyo", "seoul", "moscu", "munich", "hamburgo", "berlin", "stuttgart", "praga", "milan"},
		    {"istanbul", "madrid", "frankfurt", "paris", "roma", "dubai", "doha", "moscu", "ankara", "newyork", "tokyo", "hongkong", "singapur", "bangkok", "seoul", "izmir", "antalya", "atenas"},
		    {"newyork", "washingtondc", "losangeles", "madrid", "londres", "istanbul", "toronto", "tokyo", "frankfurt", "hongkong", "dubai", "singapur", "montreal", "mexico", "miami", "chicago", "saopaulo", "delhi", "seoul", "boston", "philadelphia", "atlanta", "orlando", "sydney"},
		    {"dubai", "doha", "abudhabi", "madrid", "londres", "paris", "frankfurt", "istanbul", "newyork", "losangeles", "toronto", "tokyo", "seoul", "delhi", "singapur", "hongkong", "bangkok", "johannesburgo", "sydney", "riyadh", "jeddah"},
		    {"tokyo", "seoul", "hongkong", "osaka", "dubai", "singapur", "bangkok", "losangeles", "sanfrancisco", "mexico", "saopaulo", "toronto", "paris", "londres", "frankfurt", "sydney", "delhi", "doha", "fukuoka", "sapporo", "okinawa"},
		    {"hongkong", "tokyo", "seoul", "bangkok", "singapur", "dubai", "newyork", "losangeles", "londres", "paris", "frankfurt", "sydney", "manila", "jakarta", "delhi", "madrid"},
		    {"singapur", "dubai", "doha", "hongkong", "tokyo", "bangkok", "kualalumpur", "sydney", "losangeles", "londres", "frankfurt", "delhi", "jakarta", "manila", "madrid"},
		    {"saopaulo", "rio", "buenosaires", "madrid", "londres", "paris", "newyork", "miami", "mexico", "toronto", "lisboa", "santiago", "bogota", "lima"},
		    {"toronto", "newyork", "montreal", "vancouver", "losangeles", "chicago", "madrid", "londres", "paris", "calgary", "ottawa"},
		    {"johannesburgo", "londres", "paris", "frankfurt", "dubai", "doha", "nairobi", "lagos", "madrid", "capetown", "durban"},
		    {"bangkok", "tokyo", "seoul", "hongkong", "singapur", "dubai", "doha", "londres", "paris", "frankfurt", "delhi", "sydney", "madrid"},
		    {"sydney", "melbourne", "brisbane", "perth", "auckland", "dubai", "singapur", "losangeles", "tokyo", "adelayde", "cairns", "newyork"},
		    {"chicago", "newyork", "washingtondc", "losangeles", "miami", "toronto", "montreal", "madrid", "londres", "paris"},
		    {"boston", "newyork", "washingtondc", "toronto", "montreal", "londres", "paris"},
		    {"washingtondc", "newyork", "boston", "miami", "chicago", "toronto", "madrid", "londres"},
		    {"montreal", "toronto", "newyork", "boston", "paris", "londres", "madrid"},
		    {"vancouver", "toronto", "montreal", "losangeles", "sanfrancisco", "tokyo", "hongkong", "seoul"},

		    // HUBS MEDIANOS
		    {"barcelona", "madrid", "paris", "roma", "londres", "lisboa", "atenas", "berlin", "munich", "amsterdam", "bilbao", "dubai", "doha", "istanbul", "sevilla", "valencia", "palma", "malaga"},
		    {"roma", "madrid", "paris", "londres", "atenas", "istanbul", "frankfurt", "barcelona", "bilbao", "viena", "zurich", "dubai", "milan", "napoles", "palermo", "catania", "florencia", "venecia"},
		    {"milan", "roma", "napoles", "venecia", "florencia", "bolonia", "madrid", "paris", "londres", "frankfurt", "barcelona"},
		    {"napoles", "roma", "milan", "paris", "londres", "frankfurt", "palermo", "catania", "florencia", "bolonia"},
		    {"florencia", "roma", "milan", "venecia", "bolonia", "napoles"},
		    {"bolonia", "roma", "milan", "venecia", "florencia", "napoles"},
		    {"venecia", "roma", "milan", "napoles", "florencia", "bolonia"},
		    {"amsterdam", "paris", "madrid", "londres", "bruselas", "berlin", "viena", "roma", "oslo", "copenhague", "rotterdam", "eindhoven"},
		    {"munich", "frankfurt", "paris", "madrid", "roma", "viena", "zurich", "berlin", "londres", "hamburgo", "stuttgart"},
		    {"lisboa", "madrid", "barcelona", "paris", "londres", "roma", "frankfurt", "amsterdam", "bruselas", "porto", "funchal"},
		    {"porto", "lisboa", "madrid", "barcelona", "paris", "londres"},
		    {"viena", "frankfurt", "munich", "madrid", "barcelona", "roma", "praga", "budapest"},
		    {"praga", "viena", "berlin", "frankfurt", "madrid", "barcelona", "paris"},
		    {"marsella", "paris", "londres", "lyon", "niza", "toulouse", "madrid", "barcelona"},
		    {"atenas", "roma", "istanbul", "madrid", "barcelona", "paris", "londres"},
		    {"zurich", "frankfurt", "munich", "viena", "madrid", "barcelona", "paris", "londres", "milan", "ginebra"},
		    {"moscu", "sanpetersburgo", "istanbul", "dubai", "paris", "frankfurt", "roma", "berlin", "doha", "ekaterimburgo"},
		    {"sanpetersburgo", "moscu", "helsinki", "estocolmo", "berlin"},
		    {"helsinki", "estocolmo", "oslo", "moscu", "berlin", "londres"},
		    {"estocolmo", "helsinki", "oslo", "copenhague", "berlin", "amsterdam"},
		    {"oslo", "estocolmo", "copenhague", "helsinki", "londres", "amsterdam"},
		    {"copenhague", "estocolmo", "oslo", "helsinki", "berlin", "amsterdam", "paris"},
		    {"bruselas", "paris", "amsterdam", "madrid", "londres", "frankfurt"},
		    {"dublin", "londres", "manchester", "edinburgo", "madrid"},
		    {"manchester", "londres", "dublin", "edinburgo", "glasgow"},
		    {"edinburgo", "londres", "glasgow", "manchester", "dublin"},
		    {"telaviv", "istanbul", "roma", "atenas", "madrid", "paris", "dubai"},
		    {"casablanca", "madrid", "lisboa", "paris", "barcelona"},
		    {"cairo", "istanbul", "roma", "atenas", "madrid", "dubai"},
		    {"nairobi", "johannesburgo", "dubai", "doha", "paris"},
		    {"lagos", "johannesburgo", "dubai", "doha", "londres"},
		    {"rio", "saopaulo", "buenosaires", "madrid", "lisboa", "miami"},
		    {"buenosaires", "saopaulo", "rio", "madrid", "barcelona", "roma", "paris", "miami"},
		    {"bogota", "madrid", "miami", "newyork", "lima", "panama"},
		    {"lima", "bogota", "santiago", "madrid", "miami"},
		    {"santiago", "buenosaires", "saopaulo", "lima", "madrid", "paris"},
		    {"delhi", "dubai", "doha", "madrid", "frankfurt", "londres", "tokyo", "bangkok"},
		    {"seoul", "tokyo", "hongkong", "singapur", "losangeles", "dubai", "frankfurt", "paris"},
		    {"osaka", "tokyo", "seoul", "hongkong", "singapur", "losangeles"},
		    {"manila", "singapur", "hongkong", "tokyo", "dubai"},
		    {"jakarta", "singapur", "hongkong", "dubai", "bangkok"},
		    {"kualalumpur", "singapur", "bangkok", "dubai", "hongkong"},
		    {"melbourne", "sydney", "brisbane", "perth", "auckland", "singapur", "dubai"},
		    {"auckland", "sydney", "melbourne", "brisbane", "singapur", "losangeles"},

		    // AEROPUERTOS PEQUEÑOS
		    {"bilbao", "madrid", "barcelona", "paris", "londres", "frankfurt", "sevilla"},
		    {"malaga", "madrid", "barcelona", "londres", "paris", "roma", "palma", "sevilla"},
		    {"sevilla", "madrid", "barcelona", "londres", "valencia", "malaga"},
		    {"alicante", "madrid", "londres", "bruselas", "barcelona", "paris"},
		    {"santander", "madrid", "barcelona", "paris", "londres"},
		    {"oviedo", "madrid", "barcelona", "londres", "bilbao"},
		    {"coruna", "madrid", "lisboa", "barcelona", "santiago"},
		    {"murcia", "madrid", "barcelona", "alicante"},
		    {"zaragoza", "barcelona", "paris", "madrid", "palma"},
		    {"palma", "madrid", "barcelona", "londres", "munich", "berlin"},
		    {"tenerife", "madrid", "barcelona", "londres", "berlin", "sevilla", "grancanaria"},
		    {"grancanaria", "madrid", "barcelona", "paris", "tenerife", "lanzarote"},
		    {"valencia", "madrid", "barcelona", "londres", "sevilla", "malaga"},
		    {"santiago", "madrid", "barcelona", "lisboa"},
		    {"catanzaro", "roma", "napoles", "milan", "bolonia"},
		    {"catania", "roma", "napoles", "milan", "paris"},
		    {"palermo", "roma", "napoles", "milan", "londres"}
	};
	
}
